import React, { useState } from 'react';
import {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    TextField,
    Button,
    Alert,
} from '@mui/material';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase/config';

interface AddEmployeeDialogProps {
    open: boolean;
    onClose: () => void;
    onSuccess: () => void;
}

const AddEmployeeDialog: React.FC<AddEmployeeDialogProps> = ({ open, onClose, onSuccess }) => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('password123'); // Default initial password
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const handleSubmit = async () => {
        if (!name || !email || !password) {
            setError('すべての項目を入力してください。');
            return;
        }

        setLoading(true);
        setError('');

        try {
            // NOTE: In a real app, we would use Firebase Admin SDK to create the Auth user.
            // Here we only create the Firestore document as a placeholder.
            // The Auth user creation logic is skipped for this client-side demo.

            await addDoc(collection(db, 'users'), {
                displayName: name,
                email: email,
                role: 'employee',
                isActive: true,
                createdAt: serverTimestamp(),
                // uid will be generated by Firestore for this doc, 
                // but ideally it should match the Auth UID.
            });

            console.log('Employee added just to Firestore (No Auth User created)');
            onSuccess();
            handleClose();
        } catch (err) {
            console.error(err);
            setError('従業員の追加に失敗しました。');
        } finally {
            setLoading(false);
        }
    };

    const handleClose = () => {
        setName('');
        setEmail('');
        setPassword('password123');
        setError('');
        onClose();
    };

    return (
        <Dialog open={open} onClose={handleClose}>
            <DialogTitle>従業員を追加</DialogTitle>
            <DialogContent>
                {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
                <TextField
                    autoFocus
                    margin="dense"
                    label="氏名"
                    type="text"
                    fullWidth
                    variant="outlined"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                />
                <TextField
                    margin="dense"
                    label="メールアドレス"
                    type="email"
                    fullWidth
                    variant="outlined"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                />
                <TextField
                    margin="dense"
                    label="初期パスワード"
                    type="text"
                    fullWidth
                    variant="outlined"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    helperText="※このデモではAuthユーザーは作成されません"
                />
            </DialogContent>
            <DialogActions>
                <Button onClick={handleClose} disabled={loading}>キャンセル</Button>
                <Button onClick={handleSubmit} variant="contained" disabled={loading}>
                    追加
                </Button>
            </DialogActions>
        </Dialog>
    );
};

export default AddEmployeeDialog;
